// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {context} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DiscoverDevices(arg1:number):Promise<Array<gui.DeviceInfo>>;

export function GetActiveTasks():Promise<Array<gui.TaskSummary>>;

export function GetConfig():Promise<gui.ConfigInfo>;

export function GetDeviceInfo():Promise<gui.DeviceInfo>;

export function GetHistory(arg1:number):Promise<Array<gui.HistoryEntry>>;

export function GetLanguage():Promise<string>;

export function GetTLSFingerprint():Promise<gui.TLSFingerprint>;

export function OpenDirDialog():Promise<string>;

export function OpenFileDialog():Promise<Array<string>>;

export function OpenPath(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDeviceName(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function StartRecv(arg1:number,arg2:string):Promise<string>;

export function StartSend(arg1:string,arg2:number,arg3:Array<string>,arg4:string):Promise<string>;

export function UpdateConfig(arg1:gui.ConfigInfo):Promise<void>;
