// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['gui']['Handler']['CancelTransfer'](arg1);
}

export function ClearHistory() {
  return window['go']['gui']['Handler']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['gui']['Handler']['DeleteHistory'](arg1);
}

export function DiscoverDevices(arg1) {
  return window['go']['gui']['Handler']['DiscoverDevices'](arg1);
}

export function GetActiveTasks() {
  return window['go']['gui']['Handler']['GetActiveTasks']();
}

export function GetConfig() {
  return window['go']['gui']['Handler']['GetConfig']();
}

export function GetDeviceInfo() {
  return window['go']['gui']['Handler']['GetDeviceInfo']();
}

export function GetHistory(arg1) {
  return window['go']['gui']['Handler']['GetHistory'](arg1);
}

export function GetLanguage() {
  return window['go']['gui']['Handler']['GetLanguage']();
}

export function GetTLSFingerprint() {
  return window['go']['gui']['Handler']['GetTLSFingerprint']();
}

export function OpenDirDialog() {
  return window['go']['gui']['Handler']['OpenDirDialog']();
}

export function OpenFileDialog() {
  return window['go']['gui']['Handler']['OpenFileDialog']();
}

export function OpenPath(arg1) {
  return window['go']['gui']['Handler']['OpenPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['gui']['Handler']['SetContext'](arg1);
}

export function SetDeviceName(arg1) {
  return window['go']['gui']['Handler']['SetDeviceName'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['gui']['Handler']['SetLanguage'](arg1);
}

export function StartRecv(arg1, arg2) {
  return window['go']['gui']['Handler']['StartRecv'](arg1, arg2);
}

export function StartSend(arg1, arg2, arg3, arg4) {
  return window['go']['gui']['Handler']['StartSend'](arg1, arg2, arg3, arg4);
}

export function UpdateConfig(arg1) {
  return window['go']['gui']['Handler']['UpdateConfig'](arg1);
}
